# Generated by Django 6.0.3 on 2026-03-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='e.g., Subaru, Kawasaki', max_length=50)),
                ('model_name', models.CharField(help_text='e.g., WRX STI, Ninja H2R', max_length=50)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTO', 'Motorcycle')], default='CAR', max_length=4)),
                ('year', models.IntegerField()),
                ('engine_specs', models.CharField(help_text='e.g., 2.5L Turbocharged Boxer, 998cc Supercharged Inline-4', max_length=150)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Any extra notes or modifications.')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
